export const THEMES = [
	'Atelier Cave Dark',
	'Atelier Cave Light',
	'Atelier Dune Dark',
	'Atelier Dune Light',
	'Atelier Estuary Dark',
	'Atelier Estuary Light',
	'Atelier Forest Dark',
	'Atelier Forest Light',
	'Atelier Heath Dark',
	'Atelier Heath Light',
	'Atelier Lakeside Dark',
	'Atelier Lakeside Light',
	'Atelier Plateau Dark',
	'Atelier Plateau Light',
	'Atelier Savanna Dark',
	'Atelier Savanna Light',
	'Atelier Seaside Dark',
	'Atelier Seaside Light',
	'Atelier Sulphurpool Dark',
	'Atelier Sulphurpool Light',
	'Summercamp',
	'Andromeda',
	'Sandcastle',
	'Solarized Dark',
	'Solarized Light',
	'Rosé Pine',
	'Rosé Pine Dawn',
	'Rosé Pine Moon',
	'One Dark',
	'One Light',
	'Ayu Dark',
	'Ayu Light',
	'Ayu Mirage',
	'Gruvbox Dark',
	'Gruvbox Dark Hard',
	'Gruvbox Dark Soft',
	'Gruvbox Light',
	'Gruvbox Light Hard',
	'Gruvbox Light Soft',
] as const

export type Theme = (typeof THEMES)[number]
